databases:
  - name: backpack
    databaseName: backpack
    user: backpack

services:
  - type: web
    name: backpack
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn backpack.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backpack
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4