# Generated by Django 4.1.5 on 2023-01-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
        migrations.AddField(
            model_name="product",
            name="photo1",
            field=models.ImageField(null=True, upload_to="product_pics"),
        ),
        migrations.AddField(
            model_name="product",
            name="photo2",
            field=models.ImageField(null=True, upload_to="product_pics"),
        ),
        migrations.AddField(
            model_name="product",
            name="photo3",
            field=models.ImageField(null=True, upload_to="product_pics"),
        ),
        migrations.AddField(
            model_name="product",
            name="photo4",
            field=models.ImageField(null=True, upload_to="product_pics"),
        ),
        migrations.AddField(
            model_name="product",
            name="photo5",
            field=models.ImageField(null=True, upload_to="product_pics"),
        ),
    ]
