# Generated by Django 4.1.5 on 2023-01-07 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_remove_product_photo_product_photo1_product_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fromOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='toOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
