# Generated by Django 4.1.5 on 2023-01-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_transaction_toowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.TimeField(),
        ),
    ]
